# Generated by Django 4.2.1 on 2024-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inm', models.CharField(max_length=25)),
                ('img', models.FileField(upload_to='pic')),
                ('prc', models.IntegerField()),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=25)),
                ('em', models.EmailField(max_length=254)),
                ('num', models.IntegerField()),
                ('pwd', models.CharField(max_length=25)),
                ('rpwd', models.CharField(max_length=25)),
            ],
        ),
    ]
