# Generated by Django 4.2.1 on 2024-04-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=25)),
                ('qty', models.IntegerField()),
                ('prc', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('fn', models.IntegerField()),
                ('cd', models.IntegerField()),
                ('ex', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
