# Generated by Django 4.2.1 on 2024-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_pay_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_table',
            name='qty',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
