# Generated by Django 4.2.1 on 2024-04-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_alter_pay_table_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_table',
            name='prc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.item_table'),
        ),
        migrations.AlterField(
            model_name='pay_table',
            name='qty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.cart_table'),
        ),
    ]
