# Generated by Django 4.2.1 on 2024-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_alter_pay_table_prc_alter_pay_table_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_table',
            name='prc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_table',
            name='qty',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
