# Generated by Django 4.2.1 on 2024-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0008_alter_pay_table_ex_alter_pay_table_fn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_table',
            name='cd',
        ),
    ]
